export const CREATE_OFFER_REQUEST = 'CREATE_OFFER_REQUEST';
export const CREATE_OFFER_SUCCESS = 'CREATE_OFFER_SUCCESS';
export const CREATE_OFFER_FAILURE = 'CREATE_OFFER_FAILURE';

export const APPLY_OFFER_REQUEST = 'APPLY_OFFER_REQUEST';
export const APPLY_OFFER_SUCCESS = 'APPLY_OFFER_SUCCESS';
export const APPLY_OFFER_FAILURE = 'APPLY_OFFER_FAILURE';

export const FETCH_OFFER_REQUEST = 'FETCH_OFFER_REQUEST';
export const FETCH_OFFER_SUCCESS = 'FETCH_OFFER_SUCCESS';
export const FETCH_OFFER_FAILURE = 'FETCH_OFFER_FAILURE';

export const DELETE_OFFER_REQUEST = 'DELETE_OFFER_REQUEST';
export const DELETE_OFFER_SUCCESS = 'DELETE_OFFER_SUCCESS';
export const DELETE_OFFER_FAILURE = 'DELETE_OFFER_FAILURE';

export const FETCH_OFFERS_REQUEST = 'FETCH_OFFERS_REQUEST';
export const FETCH_OFFERS_SUCCESS = 'FETCH_OFFERS_SUCCESS';
export const FETCH_OFFERS_FAILURE = 'FETCH_OFFERS_FAILURE';

export const FETCH_USER_OFFERS_REQUEST = 'FETCH_USER_OFFERS_REQUEST';
export const FETCH_USER_OFFERS_SUCCESS = 'FETCH_USER_OFFERS_SUCCESS';
export const FETCH_USER_OFFERS_FAILURE = 'FETCH_USER_OFFERS_FAILURE';

export const CHECK_OFFER_APPLIED_REQUEST = 'CHECK_OFFER_APPLIED_REQUEST';
export const CHECK_OFFER_APPLIED_SUCCESS = 'CHECK_OFFER_APPLIED_SUCCESS';
export const CHECK_OFFER_APPLIED_FAILURE = 'CHECK_OFFER_APPLIED_FAILURE';
